# Generated by Django 4.1.5 on 2023-03-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
